// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBq0w88Isc28kZcRXRYzT5j0cTp3HvR9k4',
    appId: '1:370595666382:web:de297a5b0be09f4986739f',
    messagingSenderId: '370595666382',
    projectId: 'chat-app-386c2',
    authDomain: 'chat-app-386c2.firebaseapp.com',
    storageBucket: 'chat-app-386c2.firebasestorage.app',
    measurementId: 'G-FLY5LTDPRE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWG-losi0qBSD1KFcsHPWpIx3Awo_y9MI',
    appId: '1:370595666382:android:b9c533032992c26586739f',
    messagingSenderId: '370595666382',
    projectId: 'chat-app-386c2',
    storageBucket: 'chat-app-386c2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFAKunxJm9zQh7begXC6F9xQLlalfjTbU',
    appId: '1:370595666382:ios:19a1a72be24b1d2486739f',
    messagingSenderId: '370595666382',
    projectId: 'chat-app-386c2',
    storageBucket: 'chat-app-386c2.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFAKunxJm9zQh7begXC6F9xQLlalfjTbU',
    appId: '1:370595666382:ios:19a1a72be24b1d2486739f',
    messagingSenderId: '370595666382',
    projectId: 'chat-app-386c2',
    storageBucket: 'chat-app-386c2.firebasestorage.app',
    iosClientId: '370595666382-91pcod361l04u663aqsqgr3srjvteqm1.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBq0w88Isc28kZcRXRYzT5j0cTp3HvR9k4',
    appId: '1:370595666382:web:36d31cebae907ded86739f',
    messagingSenderId: '370595666382',
    projectId: 'chat-app-386c2',
    authDomain: 'chat-app-386c2.firebaseapp.com',
    storageBucket: 'chat-app-386c2.firebasestorage.app',
    measurementId: 'G-ZJ74WDFQFC',
  );
}
